services:
  jenkins:
    image: jenkins/jenkins:lts # Using the official Jenkins LTS image
    container_name: jenkins
    privileged: true # Required for some Jenkins plugins
    ports:
      - "${JENKINS_PORT}:8080" # Map host port 8080 to container port 8080
      - "${JENKINS_AGENT_PORT}:50000" # For Jenkins agents
    volumes:
      - jenkins-home:/var/jenkins_home # Persist Jenkins data

volumes:
  jenkins-home:
    driver: local
